name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible:
          - 2.0.2
          - 2.1.6
          - 2.2.3
          - 2.3.3
          - 2.4.6
          - 2.5.15
          - 2.6.20
          - 2.7.16
          - 2.8.10
          - 2.9.6
        ruby:
          - 2.1.10
          - 2.2.7
          - 2.3.7
          - 2.4.9
          - 2.5.7
          - 2.6.5
          - 2.7.0

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: RUBY_VERSION=${{ matrix.ruby }} ANSIBLE_VERSION=${{ matrix.ansible }} && docker build --build-arg RUBY_VERSION=$RUBY_VERSION --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION -t pgeraghty/ansible-ruby:$RUBY_VERSION-$ANSIBLE_VERSION .
    - run: docker login -u pgeraghty -p ${{ secrets.DOCKER_PASSWORD }}
    - run: RUBY_VERSION=${{ matrix.ruby }} ANSIBLE_VERSION=${{ matrix.ansible }} && docker push pgeraghty/ansible-ruby:$RUBY_VERSION-$ANSIBLE_VERSION
